apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: kong-public-backend
  namespace: kong
spec:
  healthCheck:
    checkIntervalSec: 15
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 2
    type: HTTP
    requestPath: /lb-healthz
    port: 8000
