apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - api-moraes-lat-route.yaml
  - backendconfig.yaml
  - gatewayclass.yaml
  - gateway.yaml
  - managed-certificate.yaml
  - public-ingress.yaml
  - public-proxy-service.yaml
  - kong-lb-healthz-backend.yaml
  - kong-lb-healthz-route.yaml
  - kong-cluster-plugin-jwt.yaml
