apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - gatewayclass.yaml
  - gateway.yaml
  - api-moraes-lat-gateway.yaml
  - api-moraes-lat-route.yaml
  - kong-gateway-proxy-healthcheck.yaml
